#---------------------------------------------------------------------------
# Copyright (c) 2022 TUM. All rights reserved.
#---------------------------------------------------------------------------
FROM ghcr.io/chriswint/vldb2022-configured-crail:latest
